name = "Kapıda Ödeme"
client_id = "{{ SHOPIFY_CLIENT_ID }}"
application_url = "{{ APP_URL }}"
embedded = false

[access_scopes]
scopes = "write_orders,read_orders,read_products"

[auth]
redirect_urls = [
  "{{ APP_URL }}/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

[pos]
embedded = false
